export default [
  {
    Titulo: "Acalmar Emoções",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S",
    Duracao: "1 minuto",
    Escola: "Encantamento",
    Classes: "Clériga, Bardo",
    Descricao:
      "Você tenta suprimir emoções fortes em um grupo de \npessoas. Cada humanoide em uma esfera de 6 metros de \nraio, centrada em um ponto que você escolher dentro do \nalcance, deve realizar um teste de resistência de Carisma; \numa criatura pode escolher falhar nesse teste, se desejar. \nSe uma criatura falhar na resistência, escolha um dentre \nos dois efeitos a seguir. \n\nVocê pode suprimir qualquer efeito que esteja \ndeixando a criatura enfeitiçada ou amedrontada. Quando \nessa magia terminar, qualquer efeito suprimido volta a \nfuncionar, considerando que sua duração não tenha \nacabado nesse meio tempo.\n\nAlternativamente, você pode tornar um alvo \nindiferente às criaturas que você escolher que forem \nhostis a ele. Essa indiferença acaba se o alvo for atacado \nou ferido por uma magia ou se ele testemunhar qualquer \ndos seus amigos sendo ferido. Quando a magia terminar, \na criatura se tornará hostil novamente, a não ser que o \nMestre diga o contrário.",
    Material: "",
  },
  {
    Titulo: "Ajuda",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "8 horas",
    Escola: "Abjuração",
    Classes: "Clériga, Paladina",
    Descricao:
      "Sua magia inspira seus aliados com vigor e determinação.\nEscolha até três criaturas dentro do alcance. O máximo\nde pontos de vida e os pontos de vida atuais de cada alvo\naumentam em 5, pela duração.\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou superior, os pontos de vida dos alvos aumentam em 5\npontos adicionais para cada nível do espaço acima do o 2°.",
    Material: "uma pequena fita de tecido branco",
  },
  {
    Titulo: "Alterar-se",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "Concentração, até 1 hora",
    Escola: "Transmutação",
    Classes: "Feiticeiro, Mago",
    Descricao:
      "Você assume uma forma diferente. Quando conjurar essa\nmagia, escolha uma das seguintes opções, o efeito durará\npela duração da magia. Enquanto a magia durar, você\npode terminar uma opção com uma ação para ganhar os\nbenefícios de uma diferente.\nAdaptação Aquática. Você adapta seu corpo para\num ambiente aquático, brotando guelras e crescendo\nmembranas entre seus dedos. Você pode respirar embaixo\nd’água e ganha deslocamento de natação igual a seu\ndeslocamento terrestre.\nMudar Aparência. Você transforam sua aparência.\nVocê decide com o que você parece, incluindo altura, peso,\ntraços faciais, timbre da sua voz, comprimento do cabelo,\ncoloração e características distintas, se tiverem. Você\npode ficar parecido com um membro de outra raça, apesar\nde nenhuma de suas estatísticas mudar. Você também\nnão pode parecer com uma criatura de um tamanho\ndiferente do seu, e seu formado básico permanece o\nmesmo; se você for bípede, você não pode usar essa magia\npara se tornar quadrupede, por exemplo. A qualquer\nmomento, pela duração da magia, você pode usar sua ação\npara mudar sua aparência dessa forma, novamente.\nArmas Naturais. Você faz crescerem garras, presas,\nespinhos, chifres ou armas naturais diferentes, à sua\nescolha. Seus ataques desarmados causam 1d6 de dano de\nconcussão, perfurante ou cortante, como apropriado para\na arma natural que você escolheu, e você é proficiente\ncom seus ataques desarmados. Finalmente, a arma\nnatural é mágica e você tem +1 de bônus nas jogadas de\nataque e dano que você fizer com ela.",
    Material: "",
  },
  {
    Titulo: "Aprimorar Habilidade",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1 hora",
    Escola: "Transmutação",
    Classes: "Feiticeiro, Druida, Clériga, Bardo",
    Descricao:
      "Você toca uma criatura e a agracia com aprimoramento\nmágico. Escolha um dos efeitos a seguir; o alvo ganha esse\nefeito até o fim da magia.\nAgilidade do Gato. O alvo tem vantagem em testes\nde Destreza. Ele também não sofre dano ao cair de 6\nmetros ou menos, se não estiver incapacitado.\nEsperteza da Raposa. O alvo tem vantagem em\ntestes de Inteligência.\nEsplendor da Águia. O alvo tem vantagem em testes\nde Carisma.\nForça do Touro. O alvo tem vantagem em testes de\nForça e sua capacidade de carga é dobrada.\nSabedoria da Coruja. O alvo tem vantagem em\ntestes de Sabedoria.\nVigor do Urso. O alvo tem vantagem em testes de\nConstituição. Ele também recebe 2d6 pontos de vida\ntemporários, que são perdidos quando a magia termina.\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, você pode afetar uma criatura adicional para\ncada nível do espaço acima do 2°.",
    Material: "pelo ou penas de uma besta",
  },
  {
    Titulo: "Arma Espiritual",
    TempoConj: "1 ação bônus",
    Alcance: "18 metros",
    Componentes: "V, S",
    Duracao: "1 minuto",
    Escola: "Evocação",
    Classes: "Clériga",
    Descricao:
      "Você cria uma arma espectral flutuante, dentro do\nalcance, que permanece pela duração ou até você conjurar\nessa magia novamente. Quando você conjura essa magia,\nvocê pode realizar um ataque corpo-a-corpo com magia\ncontra uma criatura a 1,5 metro da arma. Se atingir, o\nalvo sofre dano de energia igual a 1d8 + seu modificador\nde habilidade de conjuração.\nCom uma ação bônus, no seu turno, você pode mover a\narma até 6 metros e repetir o ataque contra uma criatura\na 1,5 metro dela.\nA arma pode ter a forma que você desejar. Clérigos de\ndivindades associadas com uma arma em particular\n(como St. Cuthbert é conhecido por sua maça ou Thor por\nseu martelo) fazem o efeito dessa magia se assemelhar a\nessa arma.\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 4° nível ou\nsuperior, o dano aumenta em 1d8 para cada dois níveis do\nespaço acima do 2°.",
    Material: "",
  },
  {
    Titulo: "Arma Mágica",
    TempoConj: "1 ação bônus",
    Alcance: "Toque",
    Componentes: "V, S",
    Duracao: "Concentração, até 1 hora",
    Escola: "Transmutação",
    Classes: "Mago, Paladina",
    Descricao:
      "Você toca uma arma não-mágica. Até a magia acabar, a\narma se torna uma arma mágica com +1 de bônus nas\njogadas de ataque e jogadas de dano.\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 4° nível ou superior,\no bônus aumenta para +2. Quando você usar um espaço de\nmagia de 6° nível ou superior, o bônus aumenta para +3.",
    Material: "",
  },
  {
    Titulo: "Arrombar",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V",
    Duracao: "Instantânea",
    Escola: "Transmutação",
    Classes: "Mago, Bardo, Feiticeira",
    Descricao:
      "Escolha um objeto que você possa ver, dentro do alcance.\nO objeto pode ser uma porta, uma caixa, um baú ou um\npar de algemas, um cadeado ou outro objeto que contenha\num meio mundano ou mágico que previne o acesso.\nUm alvo que esteja fechado por uma fechadura\nmundana ou preso ou barrado torna-se destrancado,\ndestravado ou desbloqueado. Se o objeto tiver múltiplas\nfechaduras, apenas uma delas é destrancada.\nSe você escolher um alvo que esteja travado pela\nmagia tranca arcana, essa magia será suprimida por 10\nminutos, durante esse período o alvo pode ser aberto e\nfechado normalmente.\nQuando você conjurar essa magia, uma batida forte,\naudível a até 90 metros de distância, emana do objeto\nalvo",
    Material: "",
  },
  {
    Titulo: "Augúrio",
    TempoConj: "1 minuto (ritual)",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "Instantânea",
    Escola: "Adivinhação",
    Classes: "Clériga",
    Descricao:
      "Ao lançar varetas cravejados com gemas, rolar ossos de dragão, puxar cartas ornamentadas ou usar outro tipo de\nferramenta de adivinhação, você recebe um pressagio de uma entidade de outro mundo, sobre os resultados de\ncursos de ação específicos que você planeja tomar nos próximos 30 minutos. O Mestre escolhe dentre os possíveis presságios a seguir:\n• Êxito, para resultados bons\n• Fracasso, para resultados maus\n• Êxito e fracasso, para resultados bons e maus\n• Nada, para resultados que não são especialmente bons ou ruins\nA magia não leva em conta qualquer possível circunstancia que possa mudar o resultado, como a conjuração de magias adicionais ou a perda ou ganho de um companheiro.\nSe você conjurar a magia duas ou mais vezes antes de completar seu próximo descanso longo, existe uma chance cumulativa de 25 por cento de cada conjuração, depois da primeira que você fez, ter um resultado aleatório. O Mestre faz essa jogada secretamente.",
    Material:
      "varetas, ossos ou objetos similarmente marcados valendo, no mínimo, 25 po",
  },
  {
    Titulo: "Aumentar/Reduzir",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Transmutação",
    Classes: "Mago, Feiticeira",
    Descricao:
      "Você faz com que uma criatura ou um objeto que você\npossa ver dentro do alcance, fique maior ou menor, pela\nduração. Escolha entre uma criatura ou um objeto que\nnão esteja sendo carregado nem vestido. Se o alvo for\ninvoluntário, ele deve realizar um teste de resistência de\nConstituição. Se for bem sucedido, a magia não surte\nefeito.\nSe o alvo for uma criatura, tudo que ele esteja vestindo\nou carregando muda e tamanho com ela. Qualquer item\nlargado por uma criatura afetada, retorna ao seu\ntamanho natural.\nAumentar. O tamanho do alvo dobra em todas as\ndimensões e seu peso é multiplicado por oito. Esse\naumento eleva seu tamanho em uma categoria – de Médio\npara Grande, por exemplo. Se não houver espaço\nsuficiente para que o alvo dobre de tamanho, a criatura\nou objeto alcança o tamanho máximo possível no espaço\ndisponível. Até o fim da magia, o alvo também tem\nvantagem em testes de Força e testes de resistência de\nForça. O tamanho das armas do alvo crescem para se\nadequar ao seu novo tamanho. Quando essas armas são\nampliadas, os ataques do alvo com elas causam 1d4 de\ndano extra.\nReduzir. O tamanho do alvo é reduzido à metade em\ntodas as dimensões e seu peso é reduzido a um oitavo do\nnormal. Essa redução diminui o tamanho do alvo em uma\ncategoria – de Médio para Pequeno, por exemplo. Até o\nfim da magia, o alvo tem desvantagem em testes de Força\ne testes de resistência de Força. O tamanho das armas do\nalvo diminuem para se adequar ao seu novo tamanho.\nQuando essas armas são reduzidas, os ataques do alvo\ncom elas causam 1d4 de dano a menos (isso não pode\nreduzir o dano a menos de 1).",
    Material: "um pouco de pó de ferro",
  },
  {
    Titulo: "Aura Mágica de Nystul",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "24 horas",
    Escola: "Ilusão",
    Classes: "Mago",
    Descricao:
      "Você coloca uma ilusão em uma criatura ou objeto que\nvocê tocar, então magias de adivinhação revelarão\ninformações falsas sobre ele. O alvo pode ser uma criatura\nvoluntária ou um objeto que não esteja sendo carregado\nou vestido por outra criatura.\n\nQuando você conjura essa magia, escolha um ou\nambos os efeitos seguintes. O efeito permanece pela\nduração. Se você conjurar essa magia na mesma criatura\nou objeto a cada dia por 30 dias, colocando o mesmo efeito\nnele todas as vezes, a ilusão durará até ser dissipada.\n\nAura Falsa. Você modifica a forma como o alvo\naparece para magias e efeitos mágicos, como detectar\nmagia, que detectam auras mágicas. Você pode fazer um\nobjeto não-mágico parecer mágico ou mudar a aura\nmágica de um objeto para que ela pareça pertencer a\noutra escola de magia a sua escolha. Quando você usar\nesse efeito num objeto, você pode fazer a aura falsa\naparente a qualquer criatura que manusear o item.\n\nMáscara. Você modifica a forma como o alvo aparece\npara magias e efeitos que detectam tipos de criaturas,\ncomo o Sentido Divino do paladina ou o gatilho de um\nmagia símbolo. Você escolhe o tipo de criatura e outras\nmagias e efeitos mágicos consideram o alvo como se ele\nfosse uma criatura desse tipo ou tendência.",
    Material: "um pequeno quadrado de seda",
  },
  {
    Titulo: "Boca Encantada",
    TempoConj: "1 minuto (ritual)",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "Até ser dissipada",
    Escola: "Ilusão",
    Classes: "Mago, Bardo",
    Descricao:
      "Você implanta uma mensagem em um objeto dentro do\nalcance, uma mensagem que é pronunciada quando uma\ncondição de ativação é satisfeita. Escolha um objeto que\nvocê possa ver e não esteja sendo vestido ou carregado por\noutra criatura. Então, fale a mensagem, que deve conter\n25 palavras ou menos, apesar de ela poder ser entregue\ndurante um período de até 10 minutos. Finalmente, determine a circunstância que irá ativar a magia para\nque sua mensagem seja entregue.\n\nQuando essa circunstância ocorrer, a boca encantada\naparecerá no objeto e recitará a mensagem com sua voz e\ncom o mesmo volume que você falou. Se o objeto que você\nescolheu tiver uma boca ou algo semelhante a uma boca\n(por exemplo, a boca de uma estátua), a boca mágica\naparece ai, então, as palavras parecerão vir da boca do\nobjeto. Quando você conjura essa magia, você pode fazer a\nmagia acabar depois de enviar sua mensagem ou ela pode\npermanecer e repetir a mensagem sempre que a\ncircunstância de ativação ocorrer.\n\nA circunstância de ativação pode ser tão genérica ou\ntão detalhada quando você quiser, apesar de ela precisar\nser baseada em condições visuais ou audíveis que ocorram\na até 9 metros do objeto. Por exemplo, você pode instruir\na boca a falar quando uma criatura se aproximar a menos\nde 9 metros do objeto ou quando um sino de prata tocar a\nmenos de 9 metros dela.",
    Material:
      "um pedaço de favo de mel e pó de jade valendo, no mínimo, 10 po, consumidos pela magia",
  },
  {
    Titulo: "Cativar",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S",
    Duracao: "1 minuto",
    Escola: "Encantamento",
    Classes: "Bardo, Bruxa",
    Descricao:
      "Você tece um cordão de palavras distrativas, fazendo as\ncriaturas, à sua escolha, que você puder ver dentro do\nalcance e que puderem ouvir você, realizarem um teste de\nresistência de Sabedoria. Qualquer criatura que não\npuder ser enfeitiçada, passa automaticamente nesse teste\nde resistência e, se você ou seus companheiros estiverem\nlutando com a criatura, ela terá vantagem na resistência.\nSe falhar na resistência, a criatura terá desvantagem em\ntestes de Sabedoria (Percepção) feitos para notar\nqualquer criatura além de você, até a magia acabar ou até\no alvo não poder mais ouvir você. A magia acaba se você\nestiver incapacitado ou incapaz de falar.",
    Material: "",
  },
  {
    Titulo: "Cegueira/Surdez",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V",
    Duracao: "1 minuto",
    Escola: "Necromancia",
    Classes: "Bardo, Clériga, Feiticeira, Mago",
    Descricao:
      "Você pode cegar ou ensurdecer um oponente. Escolha uma\ncriatura que você possa ver dentro do alcance para fazer\num teste de resistência de Constituição. Se ela falhar,\nficará ou cega ou surda (à sua escolha) pela duração. No\nfinal de cada um dos turnos dele, o alvo pode realizar um\nteste de resistência de Constituição. Se obtiver sucesso, a\nmagia termina.\n\nEm Níveis Superiores. Se você conjurar essa magia\nusando um espaço de magia de 3° nível ou superior, você\npode afetar uma criatura adicional para cada nível de\nespaço acima do 2°.",
    Material: "",
  },
  {
    Titulo: "Chama Continua",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "Até ser dissipada",
    Escola: "Evocação",
    Classes: "Clériga, Mago",
    Descricao:
      "Uma chama, que produz iluminação equivalente a uma\ntocha, surge de um objeto que você tocar. O efeito é\nparecido com o de uma chama normal, mas ele não\nproduz calor e não consome oxigênio. Uma chama\ncontinua pode ser coberta ou escondida, mas não sufocada\nou extinta.",
    Material: "pó de rubi no valor de 50 po, consumido pela magia",
  },
  {
    Titulo: "Convocar Montaria",
    TempoConj: "10 minutos",
    Alcance: "9 metros",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Conjuração",
    Classes: "Paladina",
    Descricao:
      "Você convoca um espírito que assume a forma de uma\nmontaria excepcionalmente inteligente, forte e leal,\ncriando uma ligação duradoura com ela. Aparecendo em\num espaço desocupado dentro do alcance, a montaria\nadquire a forma que você escolher, como um cavalo de\nguerra, um pônei, um camelo, um alce ou um mastim.\n(Seu Mestre pode permitir outros animais para serem\nconvocados como montarias.) A montaria tem as\nestatísticas da forma escolhida, no entanto, ele é um\ncelestial, corruptor ou fada (à sua escolha) ao invés do seu\ntipo normal. Além disso, se sua montaria tiver\nInteligência 5 ou menor, a Inteligência dela se torna 6 e\nela ganha a capacidade de compreender um idioma, à sua\nescolha, que você fala.\n\nSua montaria serve tanto para cavalgar quando para o\ncombate e você tem uma ligação instintiva com ela que\npermite a vocês lutarem como uma unidade singular.\nEnquanto estiver montado na sua montaria, você pode\nfazer com que qualquer magia que você conjure que tenha\nalcance pessoal, também afete a sua montaria.\n\nQuando a montaria cair a 0 pontos de vida, ela\ndesaparece, não deixando qualquer corpo físico para trás.\nVocê também pode dispensar sua montaria a qualquer\nmomento, com uma ação, fazendo-a desaparecer. Em\nambos os casos, conjurar essa magia novamente\nconvocará a mesma montaria, restaurando-a ao seu\nmáximo de pontos de vida.\n\nEnquanto sua montaria estiver a até 1,5 quilômetro de\nvocê, você pode se comunicar telepaticamente com ela.\n\nVocê não pode ter mais de uma montaria ligado por\nessa magia por vez. Com uma ação, você pode liberar a\nmontaria da ligação a qualquer momento, fazendo-a\ndesaparecer.",
    Material: "",
  },
  {
    Titulo: "Cordão de Flechas",
    TempoConj: "1 ação",
    Alcance: "1.5 metros",
    Componentes: "V, S, M",
    Duracao: "8 horas",
    Escola: "Transmutação",
    Classes: "Guardião",
    Descricao:
      "Você enfinca quatro munições não-mágicas – flechas ou\nvirotes de besta – no solo dentro do alcance e conjura\nmagia neles para proteger uma área. Até a magia acabar,\nsempre que uma criatura diferente de você se aproximar\na 9 metros das munições pela primeira vez em um turno\nou terminar seu turno na área, uma das munições voa\npara atingi-la. A criatura deve ser bem sucedida num\nteste de resistência de Destreza ou sofrerá 1d6 de dano\nperfurante. A munição, então, é destruída. A magia\ntermina quando não restar nenhuma munição.\n\nQuando você conjurar essa magia, você pode designar\nquaisquer criaturas, à sua escolha, e a magia ignora-as.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, a quantidade de munições que você pode afetar\naumenta em dois para cada nível do espaço acima do 2°.",
    Material: "quatro ou mais flechas ou virotes",
  },
  {
    Titulo: "Coroa da Loucura",
    TempoConj: "1 ação",
    Alcance: "36 metros",
    Componentes: "V, S",
    Duracao: "Concentração, até 1min",
    Escola: "Encantamento",
    Classes: "Bruxa, Feiticeira, Mago, Bardo",
    Descricao:
      "Um humanoide, à sua escolha, que você possa ver dentro\ndo alcance, deve ser bem sucedido num teste de\nresistência de Sabedoria ou ficará enfeitiçado por você\npela duração. Enquanto o alvo estiver enfeitiçado dessa\nforma, uma coroa retorcida de ferro denteado aparece na\ncabeça dele e a loucura brilha em seus olhos.\n\nA criatura enfeitiçada deve usar sua ação antes de se\nmover, em cada um dos turnos dela, para realizar um\nataque corpo-a-corpo contra uma criatura, diferente de si\nmesma, que você escolher mentalmente.\n\nO alvo pode agir normalmente no turno dele se você\nnão escolher uma criatura ou se você não estiver dentro\ndo alcance.\n\nNos seus turnos subsequentes, você deve usar sua\nação para manter o controle sobre o alvo, ou a magia\ntermina. Igualmente, o alvo pode realizar um teste de\nresistência de Sabedoria no final de cada um dos turnos\ndele. Se obtiver sucesso, a magia termina.",
    Material: "",
  },
  {
    Titulo: "Crescer Espinhos",
    TempoConj: "1 ação",
    Alcance: "45 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 10min",
    Escola: "Transmutação",
    Classes: "Druida, Guardião",
    Descricao:
      "O solo em 6 metros quadrados, centrado num ponto\ndentro do alcance, se retorce e brotam cavilhas rígidas e\nespinhos. A área se torna terreno difícil pela duração.\nQuando uma criatura entrar ou se mover dentro da área,\nela sofrerá 2d4 de dano perfurante para cada 1,5 metro\nque ela atravessar.\n\nA transformação do terreno é camuflada para parecer\nnatural. Qualquer criatura que não puder ver a área no\nmomento que a magia for conjurada, deve realizar um\nteste de Sabedoria (Percepção) contra a CD da magia para\nreconhecer o terreno como perigoso, antes de adentra-lo.",
    Material:
      "sete espinhos afiados ou sete gravetos, todos com uma ponta afiada",
  },
  {
    Titulo: "Despedaçar",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Bruxa, Feiticeira, Mago, Bardo",
    Descricao:
      "Um alto som estridente, dolorosamente intenso, emerge\nde um ponto, à sua escolha, dentro do alcance. Cada\ncriatura, numa esfera de 3 metros de raio, centrada no\nponto deve fazer um teste de resistência de Constituição.\nUma criatura sofre 3d8 de dano trovejante se falhar na\nresistência ou metade desse dano se obtiver sucesso. Uma\ncriatura feita de material inorgânico como pedra, cristal\nou metal, tem desvantagem nesse teste de resistência.\n\nUm objeto não-mágico que não esteja sendo vestido ou\ncarregado, também sofre o dano, se estiver na área da\nmagia.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, o dano aumenta em 1d8 para cada nível do\nespaço acima do 2°.",
    Material: "uma lasca de mica",
  },
  {
    Titulo: "Detectar Pensamentos",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Adivinhação",
    Classes: "Bardo, Feiticeira, Mago",
    Descricao:
      "Pela duração, você pode ler os pensamentos de certas\ncriaturas. Quando você conjura essa magia e, com sua\nação a cada turno até o fim da magia, você pode focar sua\nmente em qualquer criatura que você puder ver a até 9\nmetros de você. Se a criatura escolhida possuir\nInteligência 3 ou inferior ou não falar nenhum tipo de\nidioma, a criatura não poderá ser afetada.\n\nVocê, inicialmente, descobre os pensamentos\nsuperficiais da criatura – o que está mais presente na sua\nmente no momento. Com uma ação, você pode tanto\nmudar sua atenção para os pensamentos de outra\ncriatura, como tentar sondar mais profundamente na\nmente da mesma criatura. Se você resolver sondar\nprofundamente, a criatura deve realizar um teste de\nresistência de Sabedoria. Se falhar, você ganha ciência do\nseu raciocínio (se possuir), seu estado emocional e algo\nque tome grande parte da sua mente (como algo que ele se\npreocupe, amores ou ódios). Se ele for bem sucedido, a\nmagia termina. Em ambas situações, o alvo saberá que\nvocê está sondando a mente dele e, a não ser que você\nmude sua atenção para os pensamentos de outra criatura,\na criatura pode usar a ação dela, no turno dela, para\nrealizar um teste de Inteligência resistido por seu teste de\nInteligência; se ela for bem sucedida, a magia termina\n\nPerguntas feitas diretamente para a criatura alvo,\nnormalmente moldarão o curso dos seus pensamentos,\nportanto, essa magia é particularmente eficiente como\nparte de um interrogatório.\n\nVocê pode, também, usar essa magia para detectar a\npresença que criaturas pensantes que você não possa ver.\nQuando você conjura essa magia ou, com sua ação\nenquanto ela durar, você pode procurar por pensamentos\na até 9 metros de você. A magia pode penetrar a maioria\ndas barreiras, mas é bloqueada por 30 centímetros de\nrocha, 2,5 centímetros de metal comum, uma fina camada\nde chumbo, ou 90 centímetros de madeira ou terra. Você\nnão pode detectar uma criatura com Inteligência 3 ou\ninferior ou uma que não fale qualquer idioma.\n\nUma vez que você tenha detectado a presença de uma\ncriatura dessa forma, você pode ler os pensamentos dela\npelo resto da duração, como descrito acima, mesmo que\nvocê não possa vê-la, mas ela ainda precisa estar dentro\ndo alcance.",
    Material: "um pedaço de cobre",
  },
  {
    Titulo: "Encontrar Armadilhas",
    TempoConj: "1 ação",
    Alcance: "36 metros",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Adivinhação",
    Classes: "Guardião, Druida",
    Descricao:
      "Você sente a presença de qualquer armadilha dentro do\nalcance a qual você tenha linha de visão. Uma armadilha,\npara os propósitos dessa magia, inclui qualquer coisa que\npossa causar um efeito repentino ou inesperado em você,\nconsiderado nocivo ou indesejável, que foi especificamente\nplanejado para ser por seu criador. Portanto, a magia\nsentirá a área afetada pela magia alarme, um glifo de\nvigilância ou uma armadilha mecânica de fosso, mas ela\nnão revelará uma fragilidade natural no piso, um teto\ninstável ou um sumidouro escondido.\n\nEssa magia apenas revela que existe uma magia\npresente. Você não descobre a localização de cada\narmadilha, mas você também descobre a natureza\ngenérica do perigo representando pela armadilha que\nvocê sentiu.",
    Material: "",
  },
  {
    Titulo: "Escuridão",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, M",
    Duracao: "Concentração, até 10min",
    Escola: "Evocação",
    Classes: "Bruxa, Feiticeira, Mago",
    Descricao:
      "Escuridão mágica se espalha a partir de um ponto, à sua\nescolha, dentro do alcance e preenche uma esfera de 4,5\nmetros de raio pela duração. A escuridão se estende,\ndobrando esquinas. Uma criatura com visão no escuro não\npode ver através dessa escuridão e luz não-mágica não\npode iluminar dentro dela.\n\nSe o ponto que você escolheu for um objeto que você\nesteja segurando, ou um que não esteja sendo vestido ou\ncarregado, a escuridão emanará do objeto e se moverá\ncom ele. Cobrir completamente a fonte da escuridão com\num objeto opaco, como uma vasilha ou um elmo,\nbloqueará a escuridão.\n\nSe qualquer área dessa magia sobrepor uma área de\nluz criada por uma magia de 2° ou inferior, a magia que\ncriou a luz será dissipada.",
    Material: "pelo de morcego e uma gota de piche ou pedaço de carvão",
  },
  {
    Titulo: "Esfera Flamejante",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "1 minuto",
    Escola: "Conjuração",
    Classes: "Druida, Feiticeira, Mago",
    Descricao:
      "Uma esfera de fogo, com 1,5 metro de diâmetro, aparece\nem um espaço desocupado, à sua escolha, dentro do\nalcance e permanece pela duração. Qualquer criatura que\nterminar seu turno a até 1,5 metro da esfera, deve\nrealizar um teste de resistência de Destreza. A criatura\nsofre 2d6 de dano de fogo se falhar na resistência, ou\nmetade desse dano se obtiver sucesso.\n\nCom uma ação bônus, você pode mover a esfera até 9\nmetros. Se você arremessar a esfera contra uma criatura,\nessa criatura deve realizar o teste de resistência contra o\ndano da esfera e a esfera para de se mover esse turno.\n\nQuando você move a esfera, você pode direciona-la\npara barreira de até 1,5 metro de altura e ela salta sobre\nfossos de até 3 metros de distância. A esfera incendeia\nobjetos inflamáveis que não estejam sendo vestidos ou\ncarregados e emite luz plena a 6 metros de raio e\npenumbra por mais 6 metros adicionais.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, o dano aumenta em 1d6 para cada nível do\nespaço acima do 2°.",
    Material:
      "um pouco de seco, uma pitada de enxofre e uma camada de pó de ferro",
  },
  {
    Titulo: "Esquentar Metal",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "1 minuto",
    Escola: "Transmutação",
    Classes: "Bardo, Druida",
    Descricao:
      "Escolha uma objeto manufaturado de metal, como uma\narma de metal ou uma armadura pesada ou média de\nmetal, que você possa ver dentro do alcance. Você faz com\nque o objeto brilhe vermelho-incandescente. Qualquer\ncriatura em contato físico com o objeto sofrerá 2d8 de\ndano de fogo quando você conjurar a magia. Até a magia\nacabar, você pode usar uma ação bônus, em cada um dos\nseus turnos subsequentes, para causar esse dano\nnovamente.\n\nSe uma criatura estiver segurando ou vestindo o objeto\ne sofrer o dano dele, a criatura deve ser bem sucedida\nnum teste de resistência de Constituição ou largará o\nobjeto se ela puder. Se ela não largar o objeto, ela terá\ndesvantagem em jogadas de ataque e testes de habilidade\naté o início do seu próximo turno.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, o dano aumenta em 1d8 para cada nível do\nespaço acima do 2°.",
    Material: "um pedaço de ferro e uma chama",
  },
  {
    Titulo: "Flecha Ácida de Melf",
    TempoConj: "1 ação",
    Alcance: "36 metros",
    Componentes: "V, S, M",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Mago",
    Descricao:
      "Uma flecha esverdeada cintilante voa em direção de um\nalvo dentro do alcance e explode em um jato de ácido.\nFaça um ataque à distância com magia contra o alvo. Se\natingir, o alvo sofre 4d4 de dano de ácido imediatamente e\n2d4 de dano de ácido no final do próximo turno dele. Se\nerrar, a flecha salpica o alvo com ácido, causando metade\ndo dano inicial e nenhum dano no final do próximo turno\ndele.\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, o dano (tanto inicial quanto posterior) aumenta\nem 1d4 para cada nível do espaço acima do 2°.",
    Material: "folha de ruibarbo em pó e o estômago de uma víbora",
  },
  {
    Titulo: "Força Fantasmagórica",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Ilusão",
    Classes: "Bardo, Feiticeira, Mago",
    Descricao:
      "Você constrói uma ilusão que se enraíza na mente de uma\ncriatura que você possa ver, dentro do alcance. O alvo\ndeve realizar um teste de resistência de Inteligência. Se\nfalhar na resistência, você cria um objeto, criatura ou\noutro fenômeno visível – porém, fantasmagórico – à sua\nescolha, com não mais de 3 metros cúbicos e que será\npercebido apenas pelo alvo, pela duração. Essa magia não\nafeta mortos-vivos ou constructos.\n\nO fantasma inclui som, temperatura e outros\nestímulos, também evidentes apenas para o alvo.\n\nO alvo pode usar sua ação para examinar o fantasma\ncom um teste de Inteligência (Investigação) contra a CD\nda as magia. Se for bem sucedido, o alvo percebe que o\nfantasma é uma ilusão e a magia acaba.\n\nEnquanto o alvo estiver sob efeito dessa magia, ele\nconsiderará o fantasma como sendo real. O alvo\nracionalizará quaisquer resultados ilógicos ao interagir\ncom o fantasma. Por exemplo, um alvo tentado atravessar\numa ponte fantasmagórica que atravesse um abismo,\ncairá quando pisar na ponte. Se o alvo sobreviver a queda,\nele ainda acreditará que a ponte existe e procurará outra\nexplicação para a sua queda – ele foi puxado, ele\nescorregou ou um vento forte pode ter o jogado pra fora.\n\nUm alvo afetado está tão convencido da realidade do\nfantasma que pode até mesmo sofrer dano da ilusão. Um\nfantasma criado para se parecer com uma criatura pode\natacar o alvo. Similarmente, um fantasma criado para se\nparecer com fogo, um poço de ácido ou lava, podem\nqueimar o alvo. A cada rodada, no seu turno, o fantasma\npode causar 1d6 de dano psíquico no alvo, se ele estiver\nna área do fantasma ou a 1,5 metro dele, considerando\nque a ilusão é de uma criatura ou perigo que,\nlogicamente, possa causar dano, como por atacar. O alvo\nentende o dano como sendo de um tipo apropriado para a\nilusão.",
    Material: "um pouco de lã",
  },
  {
    Titulo: "Imobilizar Pessoa",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Encantamento",
    Classes: "Bardo, Bruxa, Clériga, Druida, Feiticeira, Mago",
    Descricao:
      "Escolha um humanoide que você possa ver, dentro do\nalcance. O alvo deve ser bem sucedido num teste de\nresistência de Sabedoria ou ficará paralisado pela\nduração. Essa magia não tem efeito em mortos-vivos. No\nfinal de cada um dos turnos dele, o alvo pode realizar\noutro teste de resistência de Sabedoria. Se obtiver\nsucesso, a magia termina no alvo.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, você pode afetar um humanoide adicional para\ncada nível de magia acima do 2°. Os humanoides devem\nestar a 9 metros entre si para serem afetados.",
    Material: "uma pequena peça de ferro reta",
  },
  {
    Titulo: "Invisibilidade",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1 hora",
    Escola: "Ilusão",
    Classes: "Mago, Bruxa, Bardo, Feiticeira",
    Descricao:
      "Uma criatura que você tocar, se torna invisível até a\nmagia acabar. Qualquer coisa que o alvo esteja vestindo\nou carregando fica invisível enquanto estiver de posse do\nalvo. A magia termina para o alvo caso ele ataque ou\nconjure uma magia.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, você pode afetar um alvo adicional para cada\nnível do espaço acima do 2°.",
    Material: "uma pestana envolta em gomaarábica",
  },
  {
    Titulo: "Lâmina Flamejante",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 10min",
    Escola: "Evocação",
    Classes: "Druida",
    Descricao:
      "Você evoca uma lâmina ardente em sua mão livre. A\nlâmina é similar em tamanho e formato a uma cimitarra\ne ela permanece pela duração. Se você soltar a lâmina, ela\ndesaparece, mas você pode evocar a lâmina novamente\ncom uma ação bônus.\n\nVocê pode usar sua ação para realizar ataques corpo-acorpo \ncom magia com a lâmina ardente. Se atingir, o alvo\nsofrerá 3d6 de dano de fogo.\n\nA lâmina flamejante emite luz plena a 3 metros de\nraio e penumbra por mais 3 metros adicionais.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 4° nível ou\nsuperior, o dano aumenta em 1d6 para cada dois níveis do\nespaço acima do 2°.",
    Material: "folha de sumagre",
  },
  {
    Titulo: "Levitação",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 10min",
    Escola: "Transmutação",
    Classes: "Feiticeiro, Mago",
    Descricao:
      "Uma criatura ou objeto, à sua escolha, que você possa ver,\ndentro do alcance, ergue-se verticalmente, até 6 metros e\npermanece suspenso lá pela duração. A magia pode\nlevitar um alvo pesando até 250 quilos. Uma criatura\ninvoluntária que for bem sucedida num teste de\nresistência de Constituição não é afetada.\n\nO alvo pode se mover apenas ao puxar ou empurrar\num objeto fixo ou superfície ao seu alcance (como um\nmuro ou teto), permitindo que ele se mova como se\nestivesse escalando. Você pode mudar a altitude do alvo\nem até 6 metros em ambas as direções no seu turno. Se\nvocê for o alvo, você pode se mover para cima ou para\nbaixo como parte do seu movimento. Do contrário, você\nprecisa usar sua ação para mover o alvo, que deve\npermanecer dentro do alcance da magia.\n\nQuando a magia acaba, o alvo flutua suavemente até o\nchão, se ele ainda estiver no ar.",
    Material:
      "uma pequena presilha de couro ou um pedaço de fio dourado dobrado em forma de copo com uma haste longa em uma extremidade",
  },
  {
    Titulo: "Localizar Animais ou Plantas",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "Instantânea",
    Escola: "Adivinhação",
    Classes: "Guardião, Druida",
    Descricao:
      "Descreva ou nomeie um tipo especifico de besta ou planta.\nConcentre-se na voz da natureza ao seu redor, você\ndescobre a direção e distância da criatura ou planta mais\npróxima desse tipo dentro de 7,5 quilômetros, se houver\nalguma presente.",
    Material: "um pouco de pelo de um cão de caça",
  },
  {
    Titulo: "Localizar Objeto",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 10min",
    Escola: "Adivinhação",
    Classes: "Druida, Guardião, Mago, Paladina",
    Descricao:
      "Descreva ou nomeie um objeto que seja familiar a você.\nVocê sente a direção da localização do objeto, contanto\nque o objeto esteja a até 300 metros de você. Se o objeto\nestiver em movimento, você saberá a direção do\nmovimento dele.\n\nA magia pode localizar um objeto especifico que você,\ndesde que você já tenha o visto de perto – a até 9 metros –\npelo menos uma vez. Alternativamente, a magia pode\nlocalizar o objeto de um tipo em particular mais próximo,\ncomo certo tipo de vestuário, joia, móvel, ferramenta ou\narma.\n\nEssa magia não pode localizar um objeto se qualquer\nespessura de chumbo, até mesmo uma folha fina,\nbloquear o caminho direto entre você e o objeto.",
    Material: "um galho bifurcado",
  },
  {
    Titulo: "Lufada de Vento",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Evocação",
    Classes: "Druida, Feiticeira, Mago",
    Descricao:
      "Uma linha de vento forte, com 18 metros de comprimento\ne 3 metros de largura, é soprada de você em uma direção,\nà sua escolha, pela duração da magia. Cada criatura que\ncomeçar seu turno na linha, deve ser bem sucedida num\nteste de resistência de Força ou será empurrada 4,5\nmetros para trás, na direção seguida pela linha. Qualquer\ncriatura na linha deve gastar 3 metros de movimentação\npara cada 1,5 metro que ela se mover enquanto se\naproxima de você.\n\nAs lufadas dispersam gases ou vapores e apagam\nvelas, tochas e chamas similares desprotegidas na área.\nElas fazem com que chamas protegidas, como as de\nlanternas, vibrem descontroladamente e tenham 50 por\ncento de chance de serem extintas.\n\nCom uma ação bônus, em cada um dos seus turnos,\nantes da magia acabar, você pode mudar a direção à qual\na linha é soprada de você.",
    Material: "uma semente de legume",
  },
  {
    Titulo: "Marca da Punição",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V",
    Duracao: "Concentração, até 1min",
    Escola: "Evocação",
    Classes: "Paladina",
    Descricao:
      "Da próxima vez que você atingir uma criatura com um\nataque com arma, antes do fim da magia, a arma cintilará\ncom radiação astral quando você golpear. O ataque causa\n2d6 de dano radiante extra ao alvo, que se torna visível,\nse estava invisível, e o alvo emite penumbra em um raio\nde 1,5 metro e não pode ficar invisível até a magia acabar.\n\nEm Níveis Superiores. Se você conjurar essa magia\nusando um espaço de magia de 3° nível ou superior, o\ndano extra aumenta em 1d6 para cada nível do espaço\nacima do 2°.",
    Material: "",
  },
  {
    Titulo: "Mensageiro Animal",
    TempoConj: "1 ação (ritual)",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "24 horas",
    Escola: "Encantamento",
    Classes: "Guardião, Bardo, Druida",
    Descricao:
      "Através dessa magia, você usa um animal para entregar\numa mensagem. Escolha uma besta Miúda que você possa\nver dentro do alcance, como um esquilo, um gaio-azul ou\num morcego. Você especifica um local, que você já deve ter\nvisitado, e um remetente com uma descrição geral, como\n“um homem ou mulher vestido em um uniforme da\nguarda da cidade” ou “um anão ruivo vestindo um chapéu\npontudo”. Você também fala uma mensagem com até\nvinte e cindo palavras. A besta alvo viaja pela duração da\nmagia para o local especifico, cobrindo 75 quilômetros em\n24 horas para um mensageiro voador ou 37,5 quilômetros\npara outros animais.\n\nQuando o mensageiro chegar, ele entrega sua\nmensagem para a criatura que você descreveu, repetindo\no som da sua voz. O mensageiro fala apenas para uma\ncriatura que tenha uma descrição compatível com a que\nele recebeu. Se o mensageiro não alcançar o destino antes\ndo fim da magia, a mensagem é perdida e a besta faz seu\ncaminho de volta para onde você conjurou a magia.\n\nEm Níveis Superiores. Se você conjurar essa magia\nusando um espaço de magia de 3° nível ou superior, a\nduração da magia aumenta em 48 horas para cada nível\ndo espaço acima do 2°.",
    Material: "um punhado de comida",
  },
  {
    Titulo: "Nublar",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V",
    Duracao: "Concentração, até 1min",
    Escola: "Ilusão",
    Classes: "Feiticeiro, Mago",
    Descricao:
      "Seu corpo se torna turvo, mudando e oscilando para todos\nque puderem ver você. Pela duração, qualquer criatura\nterá desvantagem nas jogadas de ataque contra você. Um\natacante é imune a esse efeito se não depender de visão,\ncomo os que tenham percepção às cegas ou os que\npuderem ver através de ilusões, como os com visão\nverdadeira.",
    Material: "",
  },
  {
    Titulo: "Nuvem de Adagas",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Conjuração",
    Classes: "Mago, Feiticeira, Bruxa, Bardo",
    Descricao:
      "Você preenche o ar com adagas giratórias num cubo de\n1,5 metro quadrado, centrado em m ponto, à sua escolha,\ndentro do alcance. Uma criatura sofre 4d4 de dano\ncortante quando entra na área da magia pela primeira\nvez no turno dela ou começa seu turno na área.\n\nEm Níveis Superiores. Se você conjurar essa magia\nusando um espaço de magia de 3° nível ou superior, o dano\naumenta em 2d4 para cada nível do espaço acima do 2°.",
    Material: "uma lasca de vidro",
  },
  {
    Titulo: "Oração Curativa",
    TempoConj: "10 minutos",
    Alcance: "9 metros",
    Componentes: "V",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Clériga",
    Descricao:
      "Até seis criaturas, à sua escolha, que você possa ver,\ndentro do alcance, recuperam uma quantidade de pontos\nde vida igual a 2d8 + seu modificador de habilidade de\nconjuração, cada uma. Essa magia não afeta mortos-vivos\nou constructos.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, a cura aumenta em 1d8 para cada nível do\nespaço acima do 2°.",
    Material: "",
  },
  {
    Titulo: "Passo Nebuloso",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V",
    Duracao: "Instantânea",
    Escola: "Conjuração",
    Classes: "Bruxa, Feiticeira, Mago",
    Descricao:
      "Brevemente envolto por uma neblina prateada, você se\nteletransporta a até 9 metros para um espaço desocupado\nque você possa ver.",
    Material: "",
  },
  {
    Titulo: "Passos sem Pegadas",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1 hora",
    Escola: "Abjuração",
    Classes: "Druida, Guardião",
    Descricao:
      "Um véu de sombras e silencia irradia de você, encobrindo\nvocê e seus companheiros contra detecção. Pela duração,\ncada criatura, à sua escolha, a até 9 metros de você\n(incluindo você) recebe +10 de bônus em testes de\nDestreza (Furtividade) e não pode ser rastreada, exceto\npor meio mágicos. Uma criatura que receber esse bônus\nnão deixa quaisquer pegadas ou outros vestígios da sua\npassagem.",
    Material: "cinzas de uma folha de visco queimada e um ramo de pinheiro",
  },
  {
    Titulo: "Patas de Aranha",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1 hora",
    Escola: "Transmutação",
    Classes: "Bruxa, Feiticeira, Mago",
    Descricao:
      "Até a magia acabar, uma criatura voluntária que você\ntocar, recebe a habilidade de se mover para cima, para\nbaixo e através de superfícies verticais e de cabeça para\nbaixo pelos tetos, enquanto deixa suas mãos livres. O alvo\ntambém ganha deslocamento de escalada igual a seu\ndeslocamento de caminhada.",
    Material: "uma gota de betume e uma\naranha",
  },
  {
    Titulo: "Pele de Árvore",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1 hora",
    Escola: "Transmutação",
    Classes: "Druida, Guardião",
    Descricao:
      "Você toca uma criatura voluntária. Até o fim da magia, a\npele da criatura fica rígida, similar a casca de um\ncarvalho, e a CA do alvo não pode ser inferior a 16,\nindependentemente do tipo de armadura que ela esteja\nvestindo.",
    Material: "um pedaço de casca de carvalho",
  },
  {
    Titulo: "Proteção contra Veneno",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S",
    Duracao: "1 hora",
    Escola: "Abjuração",
    Classes: "Clériga, Guardião, Paladina, Druida",
    Descricao:
      "Você toca uma criatura. Se ela estiver envenenada, você\nneutraliza o veneno. Se mais de um veneno estiver\nafligindo o alvo, você neutraliza um veneno, que você\nsaiba estar presente, ou neutraliza um aleatório.\n\nPela duração, o alvo terá vantagem em testes de\nresistência para não envenenado e terá resistência a dano\nde veneno.",
    Material: "",
  },
  {
    Titulo: "Raio Ardente",
    TempoConj: "1 ação",
    Alcance: "36 metros",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Feiticeiro, Mago",
    Descricao:
      "Você cria três raios de fogo e os arremessa em alvos\ndentro do alcance. Você pode arremessa-los em um alvo\nou em vários.\n\nRealize um ataque à distância com magia para cada\nraio. Se atingir, o alvo sofrerá 2d6 de dano de fogo.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, você cria um raio adicional para cada nível do\nespaço acima do 2°.",
    Material: "",
  },
  {
    Titulo: "Raio do Enfraquecimento",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S",
    Duracao: "Concentração, até 1min",
    Escola: "Necromancia",
    Classes: "Bruxa, Mago",
    Descricao:
      "Um raio negro de energia enervante parte do seu dedo em\ndireção de uma criatura, dentro do alcance. Faça um\nataque à distância com magia contra o alvo. Se atingir, o\nalvo causará metade do dano com ataques com armas que\nusem Força, até a magia acabar.\n\nNo final de cada um dos turnos do alvo, ele pode\nrealizar um teste de resistência de Constituição contra a\nmagia. Se obtiver sucesso, a magia acaba.",
    Material: "",
  },
  {
    Titulo: "Raio Lunar",
    TempoConj: "1 ação",
    Alcance: "36 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Evocação",
    Classes: "Druida",
    Descricao:
      "Um raio prateado de luz pálida brilha para baixo em um\ncilindro com 1,5 metro de raio e 12 metros de altura,\ncentrado num ponto dentro do alcance. Até a magia\nacabar, penumbra preenche o cilindro.\n\nQuando uma criatura entrar na área da magia pela\nprimeira vez em um turno, ou começar seu turno lá, ela é\nengolfada por chamas fantasmagóricas que causam dores\nlancinantes e ela deve realizar um teste de resistência de\nConstituição. Ela sofre 2d10 de dano radiante se falhar\nna resistência ou metade desse dano se passar.\n\nUm metamorfo faz seu teste de resistência com\ndesvantagem. Se ele falhar, ele, também, reverte\ninstantaneamente para sua forma original e não pode\nassumir uma forma diferente até deixar a luz da magia.\n\nEm cada um dos seus turnos após conjurar essa\nmagia, você pode usar uma ação para mover o raio 18\nmetros em qualquer direção.\n\nEm Níveis Superiores. Quando você conjurar essa\nmagia usando um espaço de magia de 3° nível ou\nsuperior, o dano aumenta em 1d10 para cada nível do\nespaço acima do 2°.",
    Material:
      "várias sementes de qualquer planta lunar e um pedaço de feldspato opalescente",
  },
  {
    Titulo: "Reflexos",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "1 minuto",
    Escola: "Ilusão",
    Classes: "Bruxa, Feiticeira, Mago",
    Descricao:
      "Três duplicatas ilusórias de você aparecem no seu espaço.\nAté a magia acabar, as duplicatas se movem com você e\ncopiam as suas ações, trocando de posição, tornando\nimpossível rastrear qual imagem é real. Você pode usar\nsua ação para dissipar as duplicatas ilusórias.\n\nCada vez que uma criatura mirar você com um ataque\nenquanto a magia durar, role um d20 para determinar se\no ataque, em vez de você, mira uma das suas duplicatas.\n\nSe você tiver três duplicatas, você deve rolar um 6 ou\nmaior para mudar o alvo do ataque para uma duplicata.\nCom duas duplicatas, você deve rolar um 8 ou maior. Com\numa duplicata, você deve rolar um 11 ou maior.\n\nA CA de uma duplicata é igual a 10 + seu modificador\nde Destreza. Se um ataque atingir uma duplicata, ela é\ndestruída. Uma duplicata só pode ser destruída por um\nataque que a atinja. Ela ignora todos os outros danos e\nefeitos. A magia acaba quando todas as três duplicatas\nforem destruídas.\n\nUma criatura não pode ser afetada por essa magia se\nnão puder enxergar, se ela contar com outros sentidos\nalém da visão, como percepção às cegas, ou se ela puder\nperceber ilusões como falsas, como com visão verdadeira.",
    Material: "",
  },
  {
    Titulo: "Repouso Tranquilo",
    TempoConj: "1 ação (ritual)",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "10 dias",
    Escola: "Necromancia",
    Classes: "Clériga, Mago",
    Descricao:
      "Você toca um corpo ou outros restos mortais. Pela\nduração, o alvo estará protegido de decomposição e não\npode se tornar um morto-vivo.\n\nA magia também estende, efetivamente, o limite de\ntempo para que o alvo seja trazido de volta a vida, já que\nos dias passados sob a influência dessa magia não contam\nno tempo limite de tais magias, como reviver os mortos.",
    Material:
      "uma pitada de sal e uma peça de cobre colocada em cada um dos olhos do corpo, que devem permanecer ai pela duração",
  },
  {
    Titulo: "Restauração Menor",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Abjuração",
    Classes: "Bardo, Clériga, Druida, Paladina, Guardião",
    Descricao:
      "Você toca uma criatura e pode, ou acabar com uma\ndoença ou uma condição que a esteja afligindo. A condição\npode ser cega, surda, paralisada ou envenenada.",
    Material: "",
  },
  {
    Titulo: "Sentido Bestial",
    TempoConj: "1 ação (ritual)",
    Alcance: "Toque",
    Componentes: "S",
    Duracao: "Concentração, até 1 hora",
    Escola: "Adivinhação",
    Classes: "Druida, Guardião",
    Descricao:
      "Você toca uma besta voluntária. Pela duração da magia,\nvocê pode usar sua ação para ver através dos olhos e ouvir\natravés dos ouvidos da besta e continua a fazê-lo até você\nusar sua ação para retornar aos seus sentidos normais.\n\nEnquanto estiver utilizando os sentidos da besta, você\nganha os benefícios de qualquer sentido especial possuído\npela criatura, no entanto, você estará cego e surdo em\nrelação aos seus próprios sentidos.",
    Material: "",
  },
  {
    Titulo: "Silêncio",
    TempoConj: "1 ação (ritual)",
    Alcance: "36 metros",
    Componentes: "V, S",
    Duracao: "Concentração, até 10min",
    Escola: "Ilusão",
    Classes: "Bardo, Bruxa, Guardião",
    Descricao:
      "Pela duração, nenhum som pode ser criado dentro ou\natravessar uma esfera de 6 metros de raio centrada num\nponto, à sua escolha, dentro do alcance. Qualquer criatura\nou objeto totalmente dentro da esfera é imune a dano\ntrovejante e as criaturas estarão surdas enquanto\nestiverem completamente dentro dela. Conjurar magias\nque inclua a componente verbal é impossível ai.",
    Material: "",
  },
  {
    Titulo: "Sugestão",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, M",
    Duracao: "Concentração, até 8h",
    Escola: "Encantamento",
    Classes: "Bardo, Bruxa, Feiticeira, Mago",
    Descricao:
      "Você sugere um curso de atividade (limitado a uma ou\nduas sentenças) e, magicamente, influencia um criatura\nque você possa ver, dentro do alcance, e que possa ouvir e\ncompreender você. Criaturas que não podem ser\nenfeitiçadas são imunes a esse efeito. A sugestão deve ser\nformulada de modo que o curso de ação soe razoável.\nDizer para a criatura se esfaquear, se arremessar em\numa lança, tocar fogo em si mesma ou fazer algum outro\nato obviamente nocivo anulará o efeito da magia.\n\nO alvo deve realizar um teste de resistência de\nSabedoria. Se falhar na resistência, ele seguirá o curso de\nação que você descreveu, da melhor forma possível. O\ncurso de ação sugerido pode continuar por toda a duração.\nSe a atividade sugerida puder ser completada em um\ntempo menor, a magia termina quando o alvo completar o\nque lhe foi dito para que fizesse.\n\nVocê pode, também, especificar condições que irão\nativar uma atividade especial pela duração. Por exemplo,\nvocê poderia sugerir a um cavaleiro que entregasse seu\ncavalo de guerra ao primeiro mendigo que ele encontrar.\nSe a condição não for satisfeita antes da magia expirar, a\natividade não será concluída.\n\nSe você ou um dos seus companheiros causar dano a uma\ncriatura afetada por essa magia, a magia termina.",
    Material:
      "uma língua de cobra e, ou um pedaço de favo de mel ou uma gota de azeite doce",
  },
  {
    Titulo: "Teia",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1 hora",
    Escola: "Conjuração",
    Classes: "Feiticeiro, Mago",
    Descricao:
      "Você conjura uma massa de teias espessas e pegajosas\nnum ponto, à sua escolha, dentro do alcance. As teias\npreenchem um cubo de 6 metros naquele ponto, pela\nduração. As teias são terreno difícil e causam escuridão\nleve na área delas.\n\nSe as teias não estiverem sendo suportadas por duas\nmassas sólidas (como duas paredes ou árvores) ou em\ncamadas sobre um chão, parede ou teto, a teia conjurada\ndesaba sobre si mesma e a magia termina no início do seu\npróximo turno. As teias em camadas sobre uma superfície\nplana terão 1,5 metro de profundidade.\n\nCada criatura que começar seu turno nas teias ou\nentrar nelas durante seu turno, deve realizar um teste de\nresistência de Destreza. Se falhar na resistência, a\ncriatura estará impedida enquanto permanecer nas teias\nou até se libertar.\n\nUma criatura impedida pelas teias pode usar sua ação\npara realizar um teste de Força contra a CD da magia. Se\nobtiver sucesso, ela não estará mais impedida.\n\nAs teias são inflamáveis. Qualquer cubo de 1,5 metro\nde teia exposto ao fogo, é consumida por ele em 1 rodada,\ncausando 2d4 de dano de fogo a qualquer criatura que\ncomeçar seu turno nas chamas.",
    Material: "um pedaço de teia de aranha",
  },
  {
    Titulo: "Tranca Arcana",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "Até ser dissipada",
    Escola: "Abjuração",
    Classes: "Mago",
    Descricao:
      "Você toca uma porta, janela, portão, baú ou outra entrada\nfechada e ela ficará trancada pela duração. Você e as\ncriaturas que você designar, quando você conjurar essa\nmagia, podem abrir o objeto normalmente. Você também\npode definir uma senha que, quando falada a 1,5 metro do\nobjeto, suprime a magia por 1 minuto. De outra forma, ele\né intransponível até ser quebrado ou a magia seja\ndissipada ou suprimida. Conjurar arrombar no objeto\nsuprime a tranca arcana por 10 minutos.\n\nEnquanto estiver sob efeito dessa magia, o objeto é\nmais difícil de quebrar ou de forçar para abrir; a CD para\nquebra-lo ou de arromba-lo aumenta em 10.",
    Material: "pó de ouro valendo, no mínimo, 25 po, consumido pela magia",
  },
  {
    Titulo: "Truque de Corda",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "1 hora",
    Escola: "Transmutação",
    Classes: "Mago",
    Descricao:
      "Você toca um pedaço de corda que tenha até 18 metros de\ncomprimento. Uma ponta da corda então, se ergue no ar\naté toda a corda estar erguida e perpendicular ao solo. Na\nponta de cima da corda, uma entrada invisível se abre\npara um espaço extradimensional que permanece até a\nmagia acabar.\n\nO espaço extradimensional pode ser alcançado\nescalando a corda até o topo. O espaço pode abrigar até\noito criaturas Médias ou menores. A corda pode ser\npuxada para dentro do buraco, fazendo-a desaparecer\npara os observadores do lado de fora do espaço.\n\nAtaques e magias não podem ultrapassar a entrada,\nentrando ou saindo do espaço extradimensional, mas\nquem está dentro pode ver o lado de fora, como se\nestivesse olhando por uma janela de 0,9 metro por 1,5\nmetro, centrada na corda.\n\nTudo que estiver dentro do espaço extradimensional\ncai quando a magia acabar.",
    Material: "pó de extrato de milho e um laço de pergaminho trançado",
  },
  {
    Titulo: "Ver o Invisível",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "1 hora",
    Escola: "Adivinhação",
    Classes: "Bardo, Feiticeira, Mago",
    Descricao:
      "Pela duração, você vê criaturas e objetos invisíveis como\nse eles fossem visíveis e você pode ver no Plano Etéreo.\nCriaturas e objetos etéreos parecem espectrais e\ntranslúcidos.",
    Material: "um pouco de talco e um pó de prata polvilhado",
  },
  {
    Titulo: "Vínculo Protetor",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "1 hora",
    Escola: "Abjuração",
    Classes: "Bruxa",
    Descricao:
      "Essa magia protege uma criatura voluntária que você\ntocar e cria uma conexão mística entre você e o alvo até a\nmagia acabar. Enquanto o alvo estiver a até 18 metros de\nvocê, ele recebe +1 de bônus na CA, nos testes de\nresistência e terá resistência a todos os danos. No\nentanto, a cada vez que ele sofrer dano, você sofrerá a\nmesma quantidade de dano.\n\nA magia acaba se você cair a 0 pontos de vida ou se\nvocê e o alvo ficarem separados a mais de 18 metros. Ela\ntambém termina se a magia for conjurada novamente em\nquaisquer das criaturas conectadas. Você também pode\ndissipar a magia com uma ação.",
    Material:
      "um par de anéis de platina valendo, no mínimo, 50 po cada, que você e o alvo devem usar pela duração",
  },
  {
    Titulo: "Visão no Escuro",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "8 horas",
    Escola: "Transmutação",
    Classes: "Mago, Druida, Feiticeira, Guardião",
    Descricao:
      "Você toca uma criatura voluntária para conceder a ela a\nhabilidade de ver nas trevas. Pela duração, a criatura\nterá visão no escuro com alcance de 18 metros.",
    Material: "ou um pedaço de cenoura seca\nou uma ágata",
  },
  {
    Titulo: "Zona da Verdade",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S",
    Duracao: "10 minutos",
    Escola: "Encantamento",
    Classes: "Paladina, Clériga, Bardo",
    Descricao:
      "Você cria uma zona mágica protegida contra enganação,\nnuma esfera com 4,5 metros de raio, centrada num ponto,\nà sua escolha, dentro do alcance. Até a magia acabar,\numa criatura que entrar na área da magia pela primeira\nvez num turno ou começar seu turno nela, deve realizar\num teste de resistência de Carisma. Se falhar na\nresistência, a criatura não poderá mentir\ndeliberadamente enquanto estiver no raio. Você saberá\ncada criatura que passou ou falhou nesse teste de\nresistência.\n\nUma criatura afetada está ciente da magia e pode,\nportanto, evitar responder perguntas as quais ela\nnormalmente responderia com uma mentira. Tais\ncriaturas podem ser evasivas em suas respostas, contanto\nque permaneçam dentro dos limites da verdade.",
    Material: "",
  },
];
